name = "no24"
main = "src/worker.mjs"
compatibility_date = "2025-08-14"
workers_dev = true

[vars]
OPEN_METEO_URL = "https://api.open-meteo.com/v1/forecast"
METNO_UA = "no24.company24/1.0 (contact: m@fereyes.com)"

[[routes]]
pattern = "no24.fereyes.com/*"
zone_name = "fereyes.com"